### ISSUE TITLE
Font e interfaccia iPhone6

### ISSUE THREAD

**Issue by ronk222** [SoNet-2017/MOSAICON-code#1]
@tmontanaro abbiamo visto dal sito pubblicato in vetrina che su Windows non gira nessuno dei font specificati nel CSS...possiamo fare un commit per aggiungerne un altro? E scrivere nel readme o in vetrina che il sito è per mobile (iPhone6)?

Grazie!

**Comment by tmontanaro** [comment]
Si, va bene!
Tanto con i commit vi tengo d'occhio!
;-)

Il 18 lug 2017 18:05, "mastarwonki" <notifications@github.com> ha scritto:

**Comment by ronk222** [comment]
Fatto, abbiamo specificato dell'iPhone anche nel json della vetrina ma abbiamo visto che ormai il contenuto è salvato da un'altra parte, quindi abbiamo scritto la precisazione nel readme di questa repository. Grazie!

**Comment by tmontanaro** [comment]
Eh si, il json della vetrina serviva solo per lo script che ha generato il
sito! ;-)
Aggiorno la descrizione a mano domani! ;-)

E grazie.
Teo

Ps. Se trovo il modo di impostare da JavaScript la visualizzazione x mobile
la metto così non serve specificare niente.

Il 18 lug 2017 19:10, "mastarwonki" <notifications@github.com> ha scritto:

**Comment by ronk222** [comment]
Scusa Teo, ho letto solo adesso. Grazie mille a te della disponibilità!
